###服务端口号
server:
  port: 8101
###eureka 基本信息配置
spring: 
 application: 
  name: eureka-server-01
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8102/eureka/
###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: true
###因为自己是为注册中心，不需要检索服务
    fetch-registry: true